version: "3"
services:
 catalog_aplicacao:
  image: leolegends/microservices_php:latest
  deploy:
   replicas: 1
  # resources:
   # limits:
   #  cpus: "0.1"
   #  memory: 50M  
   restart_policy:
    condition: on-failure
  ports: 
   - ${HOST_PORT}:80
  volumes:
   - ${SERVICE_LOCATION}:/app
  environment:
   WEB_DOCUMENT_ROOT: /app/public
  networks:
   - ${APPLICATION_NETWORK}
 catalog_portainer:
  image: portainer/portainer
  ports:
   - ${PORTAINER_PORT}:9000
  command: --admin-password '$$2y$$05$$.SNAGNTd/re69VNoevsYFugk8I7kUoteIvhiYuP4DWCUG7D6F9evy'
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   placement:
    constraints: [node.role == manager] 
  networks:
   - ${APPLICATION_NETWORK}
 redis:
  image: bitnami/redis
  ports:
    - '6381:6379'
  volumes:
    - "./redis/:/bitnami/redis/data"
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  networks:
   - ${APPLICATION_NETWORK}
networks: 
 app_network:
